apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: sentinelstream
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sentinelstream-backend:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: PORT
              value: "3000"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: DATABASE_URL
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: WORKER_URL
              value: "http://worker:8001"
            - name: WORKER_SECRET
              value: "internal_worker_secret"
            - name: JWT_SECRET
              value: "production_secret_should_be_rotated"
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: sentinelstream
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
  selector:
    app: backend
